### ISSUE TITLE
No thumbnails when porinting from a sub folder

### ISSUE THREAD

**Issue by luckyzor** [marcolivierarsenault/moonraker-home-assistant#116]
## Version of the moonraker integration
last

## Describe your setup

RPI
Klipper, Moonraker, Mainsail

## Describe the bug

when printing from a subfolder the thumbnail will not show

## 
First of all, thanks for this integration, I wich I could have done the same, instead, I've used a rest integration in the config.yaml

I had the same issue with my integration and I solved it by picking the parent_folder of the print and add it to the path if needed
Something like this:

```
       vcore400_parent_file_path:
        friendly_name: "File Parent Path"
        value_template: '{{ states.sensor.vcore400_sensor.attributes["print_stats"]["filename"].split("/")[:-1] |join("/")}}'
       vcore400_url_thumbnail:
         friendly_name: "URL thumbnail Path"
         value_template: '{% if is_state("sensor.vcore400_parent_file_path", "") %}{{ states("sensor.vcore400_object_thumbnails") }}{% else %}{{ states("sensor.vcore400_parent_file_path") }}/{{ states("sensor.vcore400_object_thumbnails") }}{% endif %}'
       vcore400_object_thumbnails:
         friendly_name: "Object Thumbnails"
         value_template: '{{ states.sensor.vcore400_file_metadata.attributes["thumbnails"][1]["relative_path"] }}'
```

maybe this can help you fix this.
I don't know python, but as I see here, I should learn it 😄
