### ISSUE TITLE
Updates required shown

### ISSUE THREAD

**Issue by NonaSuomy** [marcolivierarsenault/moonraker-home-assistant#179]
Show the updated status of software and components 

Maybe you could make something similar or nicer that lets you tell it to update stuff as well.

I added this with a markdown card. It looked like this with the old packages yaml

![image](https://github.com/marcolivierarsenault/moonraker-home-assistant/assets/1906575/fecf46aa-2e05-45d8-b9f3-6d197a2a500b)

package yaml
```
sensor:
  - platform: rest
    name: printer_3d_updates
    unique_id: "<printerip>1cba6677-02bd-4273-9083-b8301bf6844"
    scan_interval: 1
    resource_template: "http://<printerip>:7125/machine/update/status"
    json_attributes_path: "$.result"
    json_attributes:
      - version_info
    value_template: "OK"
```
```
binary_sensor:
    - name: 3d_printer_updates
      unique_id: "<printerip>59b37837-b751-5d32-98c2-516a52edf833"
      state: >
        {% for i in printer_3d_updates.result.version_info %}
        {%- if printer_3d_updates.version_info[i].version is defined %}
        {{ i }}
        {{ printer_3d_updates.result.version_info[i].version }}
        {%- endif %}
        {% endfor %}
      availability: >
        {% set items = ['sensor.printer_3d_updates'] %}
        {{ expand(items)|rejectattr('state','in',['unknown','unavailable'])
          |list|count == items|count }}
      icon: mdi:image
      attributes:
        friendly_name: "Printer Updates"
```
markdown card:
```
{%- macro writeline(key, input, indent='') %} {%- if input is mapping %} {%- if key %} {{ indent }}{{ key }}: {%- endif %}
  {%- for k, v in input.items() %}
{{ indent + '  '}}{{ writeline(k, v, indent + '  ') }}
  {%- endfor %}
{%- elif input is iterable and input is not string %} {%- if key %} {{ indent }}{{ key }}: {%- endif %}
  {%- for v in input %}
    {{ indent }}{{ writeline('', v, indent + '  ') }}
  {%- endfor %}
{%- else %} {{ indent }}{{ key }}: {{ input }} {%- endif %} {%- endmacro %}
First line 
 {%- for name, value in state_attr('sensor.printer_3d_system_info','system_info').items() %}
  {{ name | replace("_", " ") | title() }}
  {{ writeline('', value, '') | replace("_", " ") | title() }}
{%- endfor %}
<table>
  <tr align="left"><th>Package</th><th>Version</th><th>Remote Version</th><th>Needs Update</th></tr>
{%- for name, value in state_attr('sensor.printer_3d_updates','version_info').items() %} {%- if value.full_version_string is defined %}
  <tr><td>{{ name }}</td><td>{{ value.full_version_string }}</td><td>{{ value.remote_version }}</td><td>{% if value.current_hash == value.remote_hash -%}✓ UP-TO-DATE{% else -%}✘ UPDATE-REQ!{% endif %}</td></tr>
{%- endif %} {%- endfor %} </table>
```

Thank you.
