### ISSUE TITLE
Rooted Creality K1 and sensors missing / disappearing

### ISSUE THREAD

**Issue by CloakedAlien** [marcolivierarsenault/moonraker-home-assistant#237]
Moonraker Integration: v1.0.0

Printer:
Creality K1 rooted (through official means) with Moonraker v0.8.0-206-g9ad8fed8 

First time I added the integration I was confused as to why I wasn't able to see printer state or progress. After re-adding the integration it worked and I got loads of sensors and could set up automations.

But it seems like these sensors "drop out" from the integration from time to time, making it very unstable. Re-adding the integration when the printer is in an idle state seems to fix it temporarily.

If I had to wager a guess there's some data reported by the printer while printing that sometimes throws the integration off.

I'll see if I can manage to get some logs. Is it just the normal home assistant logs?

I took a glance right now in the current working state and it seems to be spamming this while the printer is idle after just finishing a job:
```
gcode {{'size': 625995, 'modified': 1701608035.8216417, 'uuid': 'c26e62ba-0341-44d4-8248-f90ae93df493', 'slicer': 'Unknown', 'gcode_start_byte': 3606, 'gcode_end_byte': 625980, 'print_start_time': 1701608214.1534548, 'job_id': '00000D', 'filename': 'temp.gcode'}}
2:41:56 PM – (ERROR) Moonraker (custom integration) - message first occurred at 2:32:49 PM and shows up 19 times
Query Object {{'filename': 'temp.gcode'}}
2:41:56 PM – (ERROR) Moonraker (custom integration) - message first occurred at 2:32:49 PM and shows up 19 times
failed to get thumbnails {'thumbnails'}
2:41:56 PM – (ERROR) Moonraker (custom integration) - message first occurred at 2:32:49 PM and shows up 19 times
```

**Comment by gschmidl** [comment]
I just came here to look for this issue. Mine's a K1 Max and I re-added it while it's printing - I'm missing all the printing data sensors and the camera/thumbnail aren't working.

**Comment by marcolivierarsenault** [comment]
can you provide full log
https://moonraker-home-assistant.readthedocs.io/en/stable/support/logs.html#go-full-debug-log

**Comment by marcolivierarsenault** [comment]
ok there are 2 issues, 

1) for some reason your moonraker does not output all the metadata we need. 
it's returning 
```yml 
{{
'size': 2679832, 
'modified': 1701287584.973478, 
'uuid': '94b70137-f07e-439c-be9c-c8c7e12ef934', 
'slicer': 'Unknown', 
'gcode_start_byte': 25686, 
'gcode_end_byte': 2679817, 
'print_start_time': 1701671438.6942792, 
'job_id': '000013', 
'filename': 'Filament Buffer - Buffer Male-K1_0.4_Generic-PLA_1h4m.gcode'
}}
```

while we expect (according to the [doc](https://moonraker.readthedocs.io/en/latest/web_api/#get-gcode-metadata))

```yml
{
    "print_start_time": null,
    "job_id": null,
    "size": 4926481,
    "modified": 1615077020.2025201,
    "slicer": "SuperSlicer",
    "slicer_version": "2.2.52",
    "layer_height": 0.15,
    "first_layer_height": 0.2,
    "object_height": 48.05,
    "filament_total": 4056.4,
    "estimated_time": 7569,
    "thumbnails": [
        {
            "width": 32,
            "height": 32,
            "size": 2596,
            "relative_path": ".thumbs/3DBenchy_0.15mm_PLA_MK3S_2h6m-32x32.png"
        },
        {
            "width": 400,
            "height": 300,
            "size": 73308,
            "relative_path": ".thumbs/3DBenchy_0.15mm_PLA_MK3S_2h6m-400x300.png"
        }
    ],
    "first_layer_bed_temp": 60,
    "first_layer_extr_temp": 215,
    "gcode_start_byte": 79451,
    "gcode_end_byte": 4915668,
    "filename": "3DBenchy_0.15mm_PLA_MK3S_2h6m.gcode"
}
```

So either your moonraker is removing info, or your slicer is not adding it. 


2nd problem is that because of the missing info we are dividing by 0 which I can patch.

The lack of data is also the reason you don't have a thumbnail
