### ISSUE TITLE
Sensor for Last Print File & Last Print Duration

### ISSUE THREAD

**Issue by turulix** [marcolivierarsenault/moonraker-home-assistant#414]
## Is your feature request related to a problem? Please describe.

I'm trying to send myself a discord message, whenever my print finishes like octoprint does. Currentlly i simply use 
`print_duration.state` and `_filename.state` which results in this:
![image](https://github.com/user-attachments/assets/25b5a170-c659-4787-aac5-0e5be11e8cff)

## Describe your setup

Please describe your Printer setup, (especially software stack)
Ender-3 Neo, Mainsail

## Describe the solution you'd like

I want something that gives me the sate of the last print.

## Additional context

```yaml
- id: '1723558995614'
  alias: Ender3-Neo Finished Print
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.ender_3_neo_current_print_state
    from: printing
    to: complete
  condition: []
  action:
  - device_id: 18092016fea4cab2d4e30a6949e715bf
    domain: mobile_app
    type: notify
    title: 3D Druck Abgeschlossen
    message: Ender 3-Neo ist fertig mit drucken.
  - service: notify.dc_notification
    data:
      message: ''
      target:
      - '1002737271159660604'
      data:
        embed:
          title: '**Ender3-Neo Print Complete ✅**'
          description: '{% set ct = states.sensor.ender_3_neo_print_duration.state
            | float %} **File**: {{ states.sensor.ender_3_neo_filename.state | truncate(57,
            true) }}

            **Print Time**: {{ "%d" | format(ct // 60) }} hours {{ "%d" | format(int(ct
            % 60)) }} minutes {{ "%d" | format((ct % 60)*100 // 60) }} seconds

            [Check In With Quick View](http://192.168.179.26/)

            '
          color: 3066992
  mode: single
```

**Comment by marcolivierarsenault** [comment]
Here is how I do it

```yaml
alias: 3D print done
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.state
    to: complete
    for:
      hours: 0
      minutes: 1
      seconds: 0
  - platform: state
    entity_id:
      - sensor.mainsail_current_print_state
    to: complete
condition: []
action:
  - device_id: 393ca61ac995ba9fe1e881162eb40821
    domain: mobile_app
    type: notify
    title: Impression terminée
    message: 3D Printer
mode: single

```
