### ISSUE TITLE
automation help

### ISSUE THREAD

**Issue by EQNish** [marcolivierarsenault/moonraker-home-assistant#563]
I have 5 printers, I am trying to set up a automation to tell me a printer has completed a print job, but I'm pretty weak at this, I can't seem to find/understand the trigger... below is my basic attempt

`alias: 150 printing notifcation
description: ""
triggers:
  - trigger: state
    entity_id:
      - sensor.k2plus_02be_printer_state
      - sensor.k1max_150_black_printer_state
      - sensor.k1max_152_grey_printer_state
      - sensor.k1max_153_black_printer_state
      - sensor.k1max_154_black_printer_state
    from: printing
    to: ready
    for:
      hours: 0
      minutes: 0
      seconds: 5
conditions: []
actions:
actions:
  - action: notify.discord
    metadata: {}
    data:
      message: "{{ trigger.to_state.name }} is started printing"
mode: single
`

this never tells me the print has completed
also, I would like to know when then Bed reaches a set temp... was trying to use 
`      - sensor.k1max_153_black_bed_temperature
    for:
      hours: 0
      minutes: 1
      seconds: 5
    from: "20"
    to: "30"
`
but that never triggered

**Comment by OverDodo** [comment]
For the notification, I use this trigger (since I want to get notified also when it pauses/cancels whatever). So I use the "Current print state" sensor.
If you only want it for successful finishes, I think the direct status would be "Complete".
```
triggers:
  - trigger: state
    entity_id:
      - sensor.k1_max_current_print_state
    from: printing
    id: any
```

As for the second one, can you post the whole trigger? Did you use "Numeric state" as the trigger there?

Heres what I would do, using a temperature a little under what the target is (e.g. 58 if you want 60), since it can vary a bit:

```
triggers:
  - trigger: numeric_state
    entity_id:
      - sensor.k1_max_bed_temperature
    for:
      hours: 0
      minutes: 10
      seconds: 0
    above: 58
```
